language: scala

jdk: oraclejdk8

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.6
  - env: SBT_VERSION="1.1.0"
    scala: 2.12.4

script:
  - sbt ++$TRAVIS_SCALA_VERSION "^^${SBT_VERSION}"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
